services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-jogo-ibuc
    working_dir: /home/node/jogo-ibuc
    volumes:
      - .:/home/node/jogo-ibuc:cached
    ports:
      - "3000:3000"  # Para o Next.js
      - "3030:3030"  # Para o NestJS
      - "8081:8081"  # Para o Expo
    command: ["bash", "-c", "tail -f /dev/null"]
    networks:
      - devnetwork
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres-jogo-ibuc
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: quiz_ibuc
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - devnetwork

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-jogo-ibuc
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    networks:
      - devnetwork
    depends_on:
      - postgres

volumes:
  postgres-data:

networks:
  devnetwork:
