version: '3.8'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-jogo-ibuc
    working_dir: /home/node/jogo-ibuc
    volumes:
      - .:/home/node/jogo-ibuc:cached
    ports:
      - "${NODE_PORT}:3000"    # Next.js
      - "${NESTJS_PORT}:3030"  # NestJS
      - "${EXPO_PORT}:8081"    # Expo
    environment:
      - NODE_ENV=development
    command: ["bash", "-c", "tail -f /dev/null"]
    networks:
      - devnetwork
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    container_name: postgres-jogo-ibuc
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - devnetwork

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-jogo-ibuc
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - devnetwork
    depends_on:
      - postgres

  redis:
    image: redis:latest
    container_name: redis-jogo-ibuc
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - devnetwork

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander-jogo-ibuc
    environment:
      - REDIS_HOSTS=local:redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "8082:8081"
    networks:
      - devnetwork
    depends_on:
      - redis

volumes:
  postgres-data:
  redis-data:

networks:
  devnetwork:
